Updated css for sync-with-system tooltips.
ckeditor/github-writer pull request #405
Opened 2022-10-20 07:21 UTC by mateuszzagorski

After the recent editor update to v 35.2.1 it was necessary to update css for tooltips when using `sync-with-system` theme. Closing #390.

2022-10-20 14:06 UTC, mmotyczynska requested changes
Besides the comment regarding changing the tooltip background, there is still one issue we have to address. The triangle in the toolbar tooltips does not look good I guess in all theme variants. We recently solved a similar problem for [tooltips for image/table](https://github.com/ckeditor/github-writer/pull/400) so maybe you could find there some inspiration for this fix.

2022-10-21 09:20 UTC, mateuszzagorski commented on src/app/theme/panel.css
> +}
So after adding some css and a bit of tweaking of the styles we already had, it should be unified now and look like this:

<table><tbody><tr><td>sync-with-system (light)</td><td>Sync-with-system (dark)</td><td>default (light)</td><td>default (dark)</td></tr><tr><td><figure class="image"><img src="https://user-images.githubusercontent.com/11699569/197160414-e82a7a4e-4420-4cfc-89cb-5b5e2b0d96fc.png"></figure></td><td><figure class="image"><img src="https://user-images.githubusercontent.com/11699569/197160017-1a1a7eb5-5293-435e-8b76-4d4450e2822a.png"></figure></td><td><figure class="image"><img src="https://user-images.githubusercontent.com/11699569/197159952-64d7407d-bbb4-4402-b405-a7f15bd03ee7.png"></figure></td><td><figure class="image"><img src="https://user-images.githubusercontent.com/11699569/197159877-7042589f-497a-47cc-9547-775d21d57729.png"></figure></td></tr></tbody></table>

2022-10-23 17:18 UTC, mmotyczynska approved these changes
Looks good now :+1:

2022-10-23 17:19 UTC, mmotyczynska commented on src/app/theme/panel.css
> +}
OK :+1:

2022-10-23 17:21 UTC, merged